### PR TITLE
Implements commit comments and commit statuses

### PR DESCRIPTION
**Pull request by rauhryan**

### CODE REVIEW

**Comment by rauhryan** [comment]
@discorick There was some really weird stuff going on with the proxy classes

**Comment by rauhryan** [comment]
When using Comments::Proxy it I'm not exactly sure which proxy it found

It's possible it was Issues::Comments

Same applies for Commits::Proxy, I think it was picking up Git::Commits which is way different

**Comment by discorick** [comment]
Oh, thats weird - are all the specs still passing ?

**Comment by rauhryan** [comment]
Yep

**Comment by discorick** [comment]
Cool beans! :shipit:

**Pull request merged**
